#!/bin/sh
# © 2025 Nikita Karamov <me@kytta.dev>
#
# SPDX-License-Identifier: EUPL-1.2 OR AGPL-3.0-only

set -eu

.venv/bin/autopep8 --in-place --recursive "${@:-.}"
.venv/bin/ruff check --fix "${@:-.}"
"$(dirname "$0")"/style
