#!/bin/sh
# © 2025 Nikita Karamov <me@kytta.dev>
#
# SPDX-License-Identifier: EUPL-1.2 OR AGPL-3.0-only

set -eu

uv run --group lint autopep8 --in-place --recursive .
uv run --group lint ruff check --fix "${@:-.}"
"$(dirname "$0")"/style
