#!/bin/sh
# Compiles Python dependencies with pip-compile
#
# © 2025 Nikita Karamov <me@kytta.dev>
#
# SPDX-License-Identifier: EUPL-1.2 OR AGPL-3.0-only

set -eu

uv pip compile --allow-unsafe --generate-hashes --output-file=requirements.txt "${@:-pyproject.toml}"
