#!/bin/sh
# Compiles Python dependencies with pip-compile
#
# © 2023 Nikita Karamov <n.karamov@tu-braunschweig.de>
#
# SPDX-License-Identifier: EUPL-1.2 OR AGPL-3.0-only

set -eu

hatch run reqs:compile "$@"
